version: "3.9"

services:
    nginx:
        build: ./compose/nginx
        depends_on:
            - php
        ports:
            - "8080:80"
        networks:
            - laravel
        volumes:
            - ./:/var/www/html/
            - ./logs/nginx:/var/log/nginx/
        container_name: nginx

    php:
        build:
            context: .
            dockerfile: compose/php/Dockerfile
        networks:
            - laravel
        volumes:
            - ./:/var/www/html/
            - ./logs/php.log:/var/log/fpm-php.www.log
        container_name: php
        expose:
            - "9000"


networks:
    laravel:
        driver: bridge
